package com.mkierzkowski.vboard_back.exception;

public enum EntityType {
    BOARD,
    BOARD_GRANT_ADMIN_REQUEST,
    BOARD_REVOKE_ADMIN_REQUEST,
    BOARD_JOIN_REQUEST,
    BOARD_MEMBER_RESTORE_REQUEST,
    BOARD_JOIN_REQUESTS_LIST,
    BOARD_LEAVE_REQUEST,
    BOARD_UPDATE_REQUEST,
    BOARD_LIST,
    POST,
    POST_PIN_REQUEST,
    POST_UPDATE_REQUEST,
    CURRENT_PASSWORD,
    FILE,
    PROFILE_PIC,
    REFRESH_TOKEN,
    REQUEST,
    TOKEN,
    USER,
}
